#!/bin/sh

echo "Installing .emacs file to ~/.emacs ..."
cp .emacs ~/
echo "done.\n"

echo "Installing .emacs file directory to ~/.emacsd ..."
cp -r .emacsd ~/
echo "done.\n"

echo "Installing .vim directory to ~/.vim ..."
cp -r .vim ~/
echo "done.\n"

echo "Installing .vimrc config file to ~/.vimrc ..."
cp .vimrc ~/
echo "done.\n"

