#!/bin/sh

echo "Creating symlink ~/.emacs --> ~/dotfiles/.emacs ..."
ln -s ~/dotfiles/.emacs ~/.emacs
echo "done.\n"

echo "Creating symlink ~/.emacsd --> ~/dotfiles/.emacsd ..."
ln -s ~/dotfiles/.emacsd ~/.emacsd
echo "done.\n"

echo "Creating symlink ~/.vim --> ~/dotfiles/.vim ..."
ln -s ~/dotfiles/.vim ~/.vim
echo "done.\n"

echo "Creating symlink ~/ .vimrc -->  ~/dotfiles/.vimrc ..."
ln -s ~/dotfiles/.vimrc ~/.vimrc
echo "done.\n"

